// See https://aka.ms/new-console-template for more information
using System.Text.Json.Serialization;

Console.WriteLine("Hello, C#!");
throw new Exception();
//Shows Program.<Main>$(String[] args) the hidden program class generated that started in .NET 6.0 and is autogenerated in HelloCS.GlobalUsings.g.cs.

//Getting definitions
int z;
//Under public static int32 Parse(string s)
//A summary that describes the method
//Parameters like the string value that can be passed to the method
//The return value of the method, including its data type
//Three exceptions (ArgumentNullException, FormatException, OverflowException) show that we can choose to wrap a call to this method in a try statement and which exceptions to catch.